---
- name: 생성한 레지스트리 서버에 로드 & 푸시하기
  hosts: localhost
  vars:
    registry_url: 'myregistry:5000'
    image_directory: '/repository/kolla_image'
  tasks:
    - name: tar 파일 찾기
      ansible.builtin.find:
        paths: "{{ image_directory }}"
        patterns: '*.tar'
      register: tar_files

    - name: registry load
      containers.podman.podman_load:
        input: "{{ item.path }}"
      loop: "{{ tar_files.files }}"
      register: loaded_images

    - name: 이미지에 태그 지정 및 레지스트리에 푸시
      ansible.builtin.shell:
        cmd: |
          image_id=$(podman images --filter reference="{{ item.results[0].image }}:latest" --format '{{{{.ID}}}}')
          podman tag $image_id {{ registry_url }}/{{ item.item.path | basename | regex_replace('.tar$', '') }}
          podman push {{ registry_url }}/{{ item.item.path | basename | regex_replace('.tar$', '') }}
      loop: "{{ loaded_images.results }}"
      when: item.changed
