#!/bin/bash
# 실행

# htpasswd 명령사용을 위해 필요
#dnf install httpd-tools -y

# id, pw 인증을 위한 파일
#mkdir -p ./auth
#htpasswd -Bbn admin admin > auth/htpasswd
#podman run -d --rm \
#	-p 5000:5000 \
#	-v /repository/kolla.bobcat/registry:/var/lib/registry \
#        -v /repository/kolla.bobcat/registry/auth:/auth \
#	-e REGISTRY_AUTH=htpasswd \
#	-e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
#	-e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
#	--name registry \
#	--hostname registry \
#	registry:2.8.3

- hosts: localhost
  tasks:
    - name: htpasswd 명령을 위한 httpd-tools 설치
      ansible.builtin.dnf:
        name: httpd-tools
        state: present

    - name: htpasswd 저장할 위치 생성
      ansible.builtin.file:
        path: ../auth
        state: directory
        mode: '0755'      
          
    - name: htpasswd 파일 생성
      ansible.builtin.shell:
        cmd: htpasswd -Bbn admin admin > ../auth/htpasswd

    - name: 디렉토리 존재 검사(마운트 디렉토리)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ../auth

    - name: registry load
      containers.podman.podman_load:
        input: /repository/kolla_image/myregistry_5000_registry.tar
   
    - name: 레지스트리 컨테이너 실행
      containers.podman.podman_container:
        name: registry
        image: "registry:2.8.3"
        state: started
        recreate: true
        hostname: registry
        publish:
          - 5000:5000
        volumes:
          - ../auth:/auth
        env:
          REGISTRY_AUTH: "htpasswd"
          REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
          REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
        restart_policy: unless-stopped
 
   # - name: 수정할 내용 변수에 저장
   #   set_fact:
   #      registry_conf_content: |
   #        [[registry]]
   #        location = "myregistry:5000"
   #        insecure = true

    - name: /etc/containers/registries.conf 수정
      ansible.builtin.shell:
        cmd: "cp ./registries.conf  /etc/containers/registries.conf"
      become: true


