- hosts: localhost
  vars:
    image_name: rockylinux
    tag: 9.3
    change_name: rocky93-bobcat
    change_tag: 20240514
    registry_url: localhost
    save_path: '/repository/bobcat_container'
  tasks:
    - name: rockylinux9.3 다운로드
      containers.podman.podman_image:
        name: "{{ image_name }}"
        tag: "{{ tag }}"

    - name: 태그 수정
      containers.podman.podman_tag:
        image: "{{ image_name }}:{{ tag }}"
        target_names: "{{ registry_url }}/{{ change_name }}:{{ change_tag }}"
    
    - name: 컨테이너 실행
      containers.podman.podman_container:
        name: "rocky93-bobcat"
        image: "rocky93-bobcat:20240514"
        state: started
        recreate: false
        hostname: rocky93-bobcat
        volumes:
          - ../openstack/:/openstack
        restart_policy: unless-stopped
        interactive: true # option : -i
        tty: true # option -t
        command: 
          - "/bin/bash" # command : "/bin/bash"
